name: Keep Awake

on:
  schedule:
    - cron: '17 */6 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: curl -fL -sS https://~~.app/ > /dev/null
